### PR TITLE
Try to fix build failure on new OSX versions

### PR DESCRIPTION
**Pull request by honnibal**
Untested -- but based on a solution that's working in spaCy. I'm pretty sure the `is_new_osx` logic is correct.

### CODE REVIEW

**Comment by ShaktiKShrivastava** [comment]
Hi, is there any issue with this PR which is holding back the merge?

**Comment by jsekamane** [comment]
I think there is a bug in the way minor versions are detected on macOS: https://github.com/explosion/spaCy/issues/5310
Since the bug originated in [spaCy](https://github.com/explosion/spaCy), I filled the issue there.

**Comment by jsekamane** [comment]
I finally got mmh3 installed, using the following steps: 

1. I used the version of mmh3 in this pull request.
2. But, I changed the `is_new_osx()` function as described in the comment above.
3. Furthermore, _ I ran `export MACOSX_DEPLOYMENT_TARGET=10.9` in _Terminal_.
4. This finally allowing me to run `python3 setup.py install` in _Terminal_ without errors.

----

Only executing the first step, gave me a couple of `clang` warnings regarding `libstdc++` and the following error:
```console
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1
```
Executing the two first steps got rid of the warnings, but gave me the following error:
```console
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
```

**Comment by hajimes** [comment]
I finally merged this commit into master, with some revisions suggested by DomHudson and jsekamane's report on the SpaCy activity. I sincerely apologize the update was delayed this long and am grateful to developers who contributed to solve issues while I was absent.

**Pull request merged**
